region = "us-west-1"
environment ="dev"
application_name = "Word-press"
service_list = ["app"]
node_instance_type ="t2.small"
minimum_nodes = 2
desired_nodes = 2
maximum_nodes = 4
admin_access_role_name = "administrator_role"
read_access_role_name = "developer_role"
