---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-aws-test
spec:
  capacity:
    storage: 40G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-0f9440b6a91271a43
    fsType: ext4  


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-claim
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi    

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test-ebs
spec:
  volumes:
    - name: pv-aws-test
      persistentVolumeClaim:
        claimName: pv-claim
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: “/usr/share/nginx/html”
          name: pv-aws-test  #name of volume   